ALTER TABLE COMMANDE
ADD CONSTRAINT FK_Com_Cli FOREIGN KEY (Code_c) REFERENCES CLIENT (Code_c);
ALTER TABLE COMMANDE
ADD CONSTRAINT FK_Com_Ven FOREIGN KEY (Code_v) REFERENCES VENDEUR (Code_v);
ALTER TABLE LIGNECOMMANDE
ADD CONSTRAINT FK_Lig_Com FOREIGN KEY (Numero) REFERENCES COMMANDE (Numero);
ALTER TABLE LIGNECOMMANDE
ADD CONSTRAINT FK_Lig_Pro FOREIGN KEY (Reference) REFERENCES PRODUIT (Reference);
ALTER TABLE VENDEUR
ADD CONSTRAINT FK_Ven_Coi FOREIGN KEY (Code_co) REFERENCES COMMISSION (Code_co);