ALTER TABLE COMMMANDE
ADD CONSTRAINT FK_Com_Cli FOREIGN KEY (Code_c) REFERENCES CLIENT (Code_c);
ALTER TABLE COMMMANDE
ADD CONSTRAINT FK_Com_Ven FOREIGN KEY (Code_v) REFERENCES VENDEUR (Code_v);
ALTER TABLE LIGNECOMMMANDE
ADD CONSTRAINT FK_Lig_Com FOREIGN KEY (Numero) REFERENCES COMMANDE (Numero);
ALTER TABLE LIGNECOMMMANDE
ADD CONSTRAINT FK_Lig_Pro FOREIGN KEY (Reference) REFERENCES PRODUIT (Reference);
