ALTER TABLE GateauPoids
DROP CONSTRAINT FK_Gat_Pro;
ALTER TABLE BonbonPoids
DROP CONSTRAINT FK_Bpo_Pro;
ALTER TABLE BonbonPiece
DROP CONSTRAINT FK_Bpi_Pro;

ALTER TABLE GateauPoids
ADD CONSTRAINT FK_Gat_Pro FOREIGN KEY (Id_Produit) REFERENCES PRODUIT (Id_Produit);
ALTER TABLE BonbonPoids
ADD CONSTRAINT FK_Bpo_Pro FOREIGN KEY (Id_Produit) REFERENCES PRODUIT (Id_Produit);
ALTER TABLE BonbonPiece
ADD CONSTRAINT FK_Bpi_Pro FOREIGN KEY (Id_Produit) REFERENCES PRODUIT (Id_Produit);
