ALTER TABLE Facture
DROP CONSTRAINT FK_Fac_Lig;
ALTER TABLE Ligne_facture
DROP CONSTRAINT FK_Lif_Pre;
ALTER TABLE Facture
DROP CONSTRAINT FK_Fac_Lif;
ALTER TABLE Facture
ADD CONSTRAINT FK_Fac_Lig FOREIGN KEY (Compte) REFERENCES Ligue (Compte);
ALTER TABLE Ligne_Facture
ADD CONSTRAINT FK_Lif_Pre FOREIGN KEY (Code) REFERENCES Prestation (Code);
ALTER TABLE Facture
ADD CONSTRAINT FK_Fac_Lif FOREIGN KEY (NumFacture) REFERENCES Ligne_Facture (NumFacture);